# This is a basic workflow to help you get started with Actions

name: Angular NG Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ deploy ]
    paths:
      - './client'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Rebuild Angular Static Files
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Node Version to use
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with: 
          node-version: '12.x'

      # Runs a set of commands using the runners shell
      - name: Install dependencies
        run: npm ci
        working-directory: ./client

      - name: Run ng build
        run: npm run build:ci
        working-directory: ./client

      - uses: EndBug/add-and-commit@v7
        with:
          add: .
          push: true
